CREATE TABLE [dbo].[ActivityDefinition] (
    [Id]                    UNIQUEIDENTIFIER NOT NULL,
    [IdentifierId]          UNIQUEIDENTIFIER NULL,
    [Version]               NVARCHAR (50)    NULL,
    [Name]                  NVARCHAR (50)    NULL,
    [Title]                 NVARCHAR (50)    NULL,
    [Status]                NVARCHAR (50)    NULL,
    [Experimental]          BIT              NULL,
    [Date]                  DATETIME         NULL,
    [Publisher]             NVARCHAR (50)    NULL,
    [Description]           NVARCHAR (MAX)   NULL,
    [Purpose]               NVARCHAR (MAX)   NULL,
    [Usage]                 NVARCHAR (MAX)   NULL,
    [ApprovalDate]          DATETIME         NULL,
    [LastReviewDate]        DATETIME         NULL,
    [EffectiveStart]        DATETIME         NULL,
    [EffectiveEnd]          DATETIME         NULL,
    [UsageContextCode]      NVARCHAR (50)    NULL,
    [UsageContextQuantity]  DECIMAL (18, 2)  NULL,
    [UsageContextRangeLow]  INT              NULL,
    [UsageContextRangeHigh] INT              NULL,
    [Jurisdiction]          NVARCHAR (50)    NULL,
    [Topic]                 NVARCHAR (50)    NULL,
    [Contributor]           NVARCHAR (50)    NULL,
    [Contact]               NVARCHAR (50)    NULL,
    [Copyright]             NVARCHAR (50)    NULL,
    [RelatedArtifactId]     UNIQUEIDENTIFIER NULL,
    [Library]               NVARCHAR (50)    NULL,
    [Code]                  NVARCHAR (50)    NULL,
    [TimingDate]            DATETIME         NULL,
    [TimingPeriodStart]     DATETIME         NULL,
    [TimingPeriodEnd]       DATETIME         NULL,
    [TimingRangeLow]        INT              NULL,
    [TimingRangeHigh]       INT              NULL,
    [LocationId]            UNIQUEIDENTIFIER NULL,
    [ParticipantType]       NVARCHAR (50)    NULL,
    [ParticipantRoleId]     NVARCHAR (50)    NULL,
    [ProductId]             UNIQUEIDENTIFIER NULL,
    [Quantity]              INT              NULL,
    [DosageId]              UNIQUEIDENTIFIER NULL,
    [BodySite]              NVARCHAR (50)    NULL,
    [TransformId]           UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([DosageId]) REFERENCES [dbo].[Dosage] ([Id]),
    FOREIGN KEY ([IdentifierId]) REFERENCES [dbo].[Identifier] ([Id]),
    FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Location] ([Id]),
    FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Medication] ([Id]),
    FOREIGN KEY ([RelatedArtifactId]) REFERENCES [dbo].[Entity] ([Id]),
    FOREIGN KEY ([TransformId]) REFERENCES [dbo].[StructureMap] ([Id])
);

