CREATE TABLE [dbo].[AllergyIntollerance] (
    [Id]                    UNIQUEIDENTIFIER NOT NULL,
    [Identifier]            UNIQUEIDENTIFIER NULL,
    [ReasonEnded]           NVARCHAR (MAX)   NULL,
    [OnsetDate]             DATETIME         NULL,
    [OnsetAge]              DECIMAL (18, 2)  NULL,
    [OnsetPeriodStart]      DATETIME         NULL,
    [OnsetPeriodEnd]        DATETIME         NULL,
    [AllergyEndDate]        DATETIME         NULL,
    [ClinicalStatus]        NVARCHAR (MAX)   NULL,
    [VerificationStatus]    NVARCHAR (MAX)   NULL,
    [Criticality]           NVARCHAR (MAX)   NULL,
    [Code]                  NVARCHAR (MAX)   NULL,
    [Type]                  NVARCHAR (MAX)   NULL,
    [Category]              NVARCHAR (MAX)   NULL,
    [Subject]               UNIQUEIDENTIFIER NULL,
    [AssertedDate]          DATETIME         NULL,
    [Asserter]              UNIQUEIDENTIFIER NULL,
    [Recorder]              UNIQUEIDENTIFIER NULL,
    [LastOccurance]         DATETIME         NULL,
    [NoteAuthored]          DATETIME         NULL,
    [NoteAuthor]            UNIQUEIDENTIFIER NULL,
    [ReactionSubstance]     NVARCHAR (MAX)   NULL,
    [ReactionManifestation] NVARCHAR (MAX)   NULL,
    [ReactionDescription]   NVARCHAR (MAX)   NULL,
    [ReactionExposureRate]  NVARCHAR (MAX)   NULL,
    [Encounter]             UNIQUEIDENTIFIER NOT NULL,
    [Evidence]              UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK__AllergyI__A2B5777CD5983ADB] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK__AllergyIn__Asser__2DE6D218] FOREIGN KEY ([Asserter]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK__AllergyIn__Ident__2BFE89A6] FOREIGN KEY ([Identifier]) REFERENCES [dbo].[Identifier] ([Id]),
    CONSTRAINT [FK__AllergyIn__NoteA__31B762FC] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Patient] ([Id]),
    CONSTRAINT [FK__AllergyIn__Recor__2FCF1A8A] FOREIGN KEY ([Recorder]) REFERENCES [dbo].[Practicioner] ([Id]),
    CONSTRAINT [FK__AllergyIn__Subje__2CF2ADDF] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]),
    CONSTRAINT [FK_AllergyIntollerance_DiagnosticReport] FOREIGN KEY ([Evidence]) REFERENCES [dbo].[DiagnosticReport] ([Id]),
    CONSTRAINT [FK_AllergyIntollerance_Encounter] FOREIGN KEY ([Encounter]) REFERENCES [dbo].[Encounter] ([Id]),
    CONSTRAINT [FK_AllergyIntollerance_Entity] FOREIGN KEY ([Recorder]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK_AllergyIntollerance_Entity1] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK_AllergyIntollerance_Entity2] FOREIGN KEY ([Asserter]) REFERENCES [dbo].[Entity] ([Id])
);

