CREATE TABLE [dbo].[Condition] (
    [Id]                   UNIQUEIDENTIFIER NOT NULL,
    [Identifier]           UNIQUEIDENTIFIER NULL,
    [ActualProblem]        UNIQUEIDENTIFIER NULL,
    [ProblemSignificance]  NVARCHAR (MAX)   NULL,
    [Episode]              NVARCHAR (MAX)   NULL,
    [ClinicalStatus]       NVARCHAR (MAX)   NULL,
    [VerificationStatus]   NVARCHAR (MAX)   NULL,
    [Severity]             NVARCHAR (MAX)   NULL,
    [Code]                 NVARCHAR (MAX)   NULL,
    [BodySite]             NVARCHAR (MAX)   NULL,
    [Subject]              UNIQUEIDENTIFIER NULL,
    [Context]              UNIQUEIDENTIFIER NULL,
    [OnsetDate]            DATETIME         NULL,
    [OnsetAge]             DECIMAL (18, 2)  NULL,
    [OnsetPeriodStart]     DATETIME         NULL,
    [OnsetPeriodEnd]       DATETIME         NULL,
    [AbatementDate]        DATETIME         NULL,
    [AbatementAge]         DECIMAL (18, 2)  NULL,
    [AbatementPeriodStart] DATETIME         NULL,
    [AbatementPeriodEnd]   DATETIME         NULL,
    [Abatement]            BIT              NULL,
    [AssertedDate]         DATETIME         NOT NULL,
    [Asserter]             UNIQUEIDENTIFIER NOT NULL,
    [EvidenceCodes]        NVARCHAR (MAX)   NULL,
    [NoteText]             NVARCHAR (MAX)   NULL,
    [NoteAuthored]         DATETIME         NULL,
    [NoteAuthor]           UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK__Conditio__A2B5777CD924092C] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK__Condition__Actua__3E1D39E1] FOREIGN KEY ([ActualProblem]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK__Condition__Asser__42E1EEFE] FOREIGN KEY ([Asserter]) REFERENCES [dbo].[Practicioner] ([Id]),
    CONSTRAINT [FK__Condition__Conte__41EDCAC5] FOREIGN KEY ([Context]) REFERENCES [dbo].[Encounter] ([Id]),
    CONSTRAINT [FK__Condition__Ident__3D2915A8] FOREIGN KEY ([Identifier]) REFERENCES [dbo].[Identifier] ([Id]),
    CONSTRAINT [FK__Condition__NoteA__43D61337] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK__Condition__Subje__40F9A68C] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id])
);

