CREATE TABLE [dbo].[Immunization] (
    [Id]                   NVARCHAR (255)   NOT NULL,
    [Status]               NVARCHAR (255)   NULL,
    [Type]                 NVARCHAR (255)   NULL,
    [Class]                NVARCHAR (255)   NULL,
    [SubjectId]            UNIQUEIDENTIFIER NULL,
    [EncounterId]          UNIQUEIDENTIFIER NULL,
    [ActorId]              UNIQUEIDENTIFIER NULL,
    [LocationId]           UNIQUEIDENTIFIER NOT NULL,
    [ParentPresent]        BIT              NULL,
    [RecordedDate]         DATETIME         NULL,
    [Date]                 DATETIME         NULL,
    [PrimarySource]        BIT              NULL,
    [LotNumber]            NVARCHAR (255)   NULL,
    [Site]                 NVARCHAR (255)   NULL,
    [Route]                NVARCHAR (255)   NULL,
    [RouteText]            NVARCHAR (255)   NULL,
    [NoteAuthorId]         UNIQUEIDENTIFIER NULL,
    [NoteText]             NVARCHAR (MAX)   NULL,
    [NoteDate]             DATETIME         NULL,
    [ExpirationDate]       DATETIME         NULL,
    [VaccinationProcedure] NVARCHAR (255)   NULL,
    [VaccinationCode]      NVARCHAR (255)   NULL,
    [DoseQuantity]         DECIMAL (18, 2)  NULL,
    [ReactionReported]     BIT              NULL,
    [ReactionDetailId]     UNIQUEIDENTIFIER NULL,
    [ReactionDate]         DATETIME         NULL,
    [DoseSequence]         INT              NULL,
    [Description]          NVARCHAR (MAX)   NULL,
    [AuthorityId]          UNIQUEIDENTIFIER NULL,
    [Series]               NVARCHAR (255)   NULL,
    [SeriesDoses]          INT              NULL,
    [TargetDisease]        NVARCHAR (255)   NULL,
    [DoseStatus]           NVARCHAR (255)   NULL,
    [DoseStatusReason]     NVARCHAR (255)   NULL,
    [EntityId]             UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK__Immuniza__A2B5777C37B1E40D] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK__Immunizat__Actor__71D1E811] FOREIGN KEY ([ActorId]) REFERENCES [dbo].[Practicioner] ([Id]),
    CONSTRAINT [FK__Immunizat__Autho__75A278F5] FOREIGN KEY ([AuthorityId]) REFERENCES [dbo].[Organization] ([Id]),
    CONSTRAINT [FK__Immunizat__Encou__70DDC3D8] FOREIGN KEY ([EncounterId]) REFERENCES [dbo].[Encounter] ([Id]),
    CONSTRAINT [FK__Immunizat__Locat__72C60C4A] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Location] ([Id]),
    CONSTRAINT [FK__Immunizat__NoteA__73BA3083] FOREIGN KEY ([NoteAuthorId]) REFERENCES [dbo].[Practicioner] ([Id]),
    CONSTRAINT [FK__Immunizat__React__74AE54BC] FOREIGN KEY ([ReactionDetailId]) REFERENCES [dbo].[Observation] ([Id]),
    CONSTRAINT [FK__Immunizat__Subje__6FE99F9F] FOREIGN KEY ([SubjectId]) REFERENCES [dbo].[Patient] ([Id]),
    CONSTRAINT [FK_Immunization_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id])
);

