CREATE TABLE [dbo].[Patient] (
    [Id]                          UNIQUEIDENTIFIER NOT NULL,
    [OrganisationGuid]            UNIQUEIDENTIFIER NOT NULL,
    [UsualGpUserInRoleGuid]       NVARCHAR (255)   NOT NULL,
    [Sex]                         NVARCHAR (255)   NULL,
    [DateOfBirthUTC]              DATETIME         NOT NULL,
    [DateOfDeathUTC]              DATETIME         NULL,
    [Title]                       NVARCHAR (255)   NULL,
    [GivenName]                   NVARCHAR (255)   NOT NULL,
    [MiddleNames]                 NVARCHAR (MAX)   NULL,
    [Surname]                     NVARCHAR (255)   NOT NULL,
    [DateOfRegistrationUTC]       DATETIME         NULL,
    [NhsNumber]                   NVARCHAR (255)   NULL,
    [PatientNumber]               NVARCHAR (255)   NULL,
    [PatientTypeDescription]      NVARCHAR (255)   NOT NULL,
    [DummyType]                   NVARCHAR (255)   NULL,
    [ResidentialInstituteCode]    NVARCHAR (255)   NOT NULL,
    [NHSNumberStatus]             NVARCHAR (255)   NULL,
    [CarerName]                   NVARCHAR (255)   NULL,
    [CarerRelation]               NVARCHAR (255)   NULL,
    [PersonGuid]                  NVARCHAR (255)   NULL,
    [DateOfDeactivation]          DATETIME         NULL,
    [Deleted]                     BIT              NULL,
    [Active]                      BIT              NULL,
    [SpineSensitive]              BIT              NULL,
    [IsConfidential]              BIT              NULL,
    [EmailAddress_Address]        NVARCHAR (255)   NULL,
    [EmailAddress_DisplayName]    NVARCHAR (255)   NULL,
    [HomePhone]                   NVARCHAR (20)    NULL,
    [MobilePhone]                 NVARCHAR (20)    NULL,
    [ExternalUsualGPGuid]         NVARCHAR (255)   NULL,
    [ExternalUsualGP]             NVARCHAR (255)   NULL,
    [ExternalUsualGPOrganisation] NVARCHAR (255)   NULL,
    [ProcessingId]                NVARCHAR (255)   NULL,
    [Ethnicity]                   NVARCHAR (255)   NULL,
    [Religion]                    NVARCHAR (255)   NULL,
    CONSTRAINT [PK__Patient__DBA60F19AE6332BC] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Patient_Organization] FOREIGN KEY ([OrganisationGuid]) REFERENCES [dbo].[Organization] ([Id])
);

