CREATE TABLE [dbo].[ReferralRequest] (
    [Id]                  UNIQUEIDENTIFIER NOT NULL,
    [Identifier]          UNIQUEIDENTIFIER NULL,
    [ActivityDefinition]  UNIQUEIDENTIFIER NULL,
    [Status]              NVARCHAR (MAX)   NULL,
    [Intent]              NVARCHAR (MAX)   NULL,
    [Type]                NVARCHAR (MAX)   NULL,
    [Priority]            NVARCHAR (MAX)   NULL,
    [ServiceRequested]    NVARCHAR (MAX)   NULL,
    [Subject]             UNIQUEIDENTIFIER NULL,
    [Context]             UNIQUEIDENTIFIER NULL,
    [OccurrenceDate]      DATETIME         NULL,
    [OccurrenceDateStart] DATETIME         NULL,
    [OccurrenceDateEnd]   DATETIME         NULL,
    [AuthoredOn]          DATETIME         NULL,
    [Requester]           UNIQUEIDENTIFIER NULL,
    [OnBehalfOf]          UNIQUEIDENTIFIER NULL,
    [Recipient]           UNIQUEIDENTIFIER NULL,
    [Description]         NVARCHAR (MAX)   NULL,
    [NoteAuthor]          UNIQUEIDENTIFIER NULL,
    [NoteText]            NVARCHAR (MAX)   NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ReferralRequest_Entity] FOREIGN KEY ([Context]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK_ReferralRequest_Entity1] FOREIGN KEY ([Requester]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK_ReferralRequest_Entity2] FOREIGN KEY ([Recipient]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK_ReferralRequest_Entity3] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK_ReferralRequest_Organization] FOREIGN KEY ([OnBehalfOf]) REFERENCES [dbo].[Organization] ([Id]),
    CONSTRAINT [FK_ReferralRequest_Patient] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id])
);

