CREATE TABLE [dbo].[Specimen] (
    [Id]                    UNIQUEIDENTIFIER NOT NULL,
    [IdentifierId]          UNIQUEIDENTIFIER NULL,
    [AccessionIdentifierId] UNIQUEIDENTIFIER NULL,
    [Status]                NVARCHAR (20)    NULL,
    [Type]                  NVARCHAR (20)    NULL,
    [SubjectId]             UNIQUEIDENTIFIER NULL,
    [ReceivedTime]          DATETIME         NULL,
    [ParentId]              UNIQUEIDENTIFIER NULL,
    [Request]               UNIQUEIDENTIFIER NULL,
    [FastingValueCode]      NVARCHAR (20)    NULL,
    [FastingDurationValue]  DECIMAL (18, 2)  NULL,
    [CollectorId]           UNIQUEIDENTIFIER NULL,
    [Collected]             DATETIME         NULL,
    [CollectedQuantity]     INT              NULL,
    [CollectionMethod]      NVARCHAR (20)    NULL,
    [CollectionBodySite]    NVARCHAR (20)    NULL,
    [ContainerIdentifierId] UNIQUEIDENTIFIER NULL,
    [SpecimenQuantity]      INT              NULL,
    [ContainerCapacity]     INT              NULL,
    [NoteText]              NVARCHAR (MAX)   NULL,
    [NoteAuthored]          DATETIME         NULL,
    [NoteAuthorId]          UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([AccessionIdentifierId]) REFERENCES [dbo].[Identifier] ([Id]),
    FOREIGN KEY ([CollectorId]) REFERENCES [dbo].[Practicioner] ([Id]),
    FOREIGN KEY ([ContainerIdentifierId]) REFERENCES [dbo].[Identifier] ([Id]),
    FOREIGN KEY ([IdentifierId]) REFERENCES [dbo].[Identifier] ([Id]),
    FOREIGN KEY ([NoteAuthorId]) REFERENCES [dbo].[Entity] ([Id]),
    FOREIGN KEY ([ParentId]) REFERENCES [dbo].[Specimen] ([Id]),
    FOREIGN KEY ([SubjectId]) REFERENCES [dbo].[Patient] ([Id]),
    CONSTRAINT [FK_Specimen_ProcedureRequest] FOREIGN KEY ([Request]) REFERENCES [dbo].[ProcedureRequest] ([Id])
);

