//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin_Location()
        {
            this.Admin_Location1 = new HashSet<Admin_Location>();
            this.Admin_Organisation = new HashSet<Admin_Organisation>();
            this.Admin_OrganisationLocation = new HashSet<Admin_OrganisationLocation>();
            this.Appointment_Session = new HashSet<Appointment_Session>();
        }
    
        public string LocationGuid { get; set; }
        public string LocationName { get; set; }
        public string LocationTypeDescription { get; set; }
        public string ParentLocationGuid { get; set; }
        public string OpenDate { get; set; }
        public string CloseDate { get; set; }
        public string MainContactName { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string HouseNameFlatNumber { get; set; }
        public string NumberAndStreet { get; set; }
        public string Village { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string Deleted { get; set; }
        public string ProcessingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_Location> Admin_Location1 { get; set; }
        public virtual Admin_Location Admin_Location2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_Organisation> Admin_Organisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_OrganisationLocation> Admin_OrganisationLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment_Session> Appointment_Session { get; set; }
    }
}
