//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_OrganisationLocation
    {
        public string OrganisationGuid { get; set; }
        public string LocationGuid { get; set; }
        public string IsMainLocation { get; set; }
        public string Deleted { get; set; }
        public string ProcessingId { get; set; }
    
        public virtual Admin_Location Admin_Location { get; set; }
        public virtual Admin_Organisation Admin_Organisation { get; set; }
    }
}
