//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_UserInRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin_UserInRole()
        {
            this.Admin_Patient = new HashSet<Admin_Patient>();
            this.Admin_Patient1 = new HashSet<Admin_Patient>();
            this.Appointment_SessionUser = new HashSet<Appointment_SessionUser>();
            this.CareRecord_Consultation = new HashSet<CareRecord_Consultation>();
            this.CareRecord_Consultation1 = new HashSet<CareRecord_Consultation>();
            this.CareRecord_Diary = new HashSet<CareRecord_Diary>();
            this.CareRecord_Diary1 = new HashSet<CareRecord_Diary>();
            this.CareRecord_Observation = new HashSet<CareRecord_Observation>();
            this.CareRecord_Observation1 = new HashSet<CareRecord_Observation>();
            this.CareRecord_Problem = new HashSet<CareRecord_Problem>();
            this.Prescribing_DrugRecord = new HashSet<Prescribing_DrugRecord>();
            this.Prescribing_DrugRecord1 = new HashSet<Prescribing_DrugRecord>();
            this.Prescribing_IssueRecord = new HashSet<Prescribing_IssueRecord>();
            this.Prescribing_IssueRecord1 = new HashSet<Prescribing_IssueRecord>();
        }
    
        public string UserInRoleGuid { get; set; }
        public string OrganisationGuid { get; set; }
        public string Title { get; set; }
        public string GivenName { get; set; }
        public string Surname { get; set; }
        public string JobCategoryCode { get; set; }
        public string JobCategoryName { get; set; }
        public string ContractStartDate { get; set; }
        public string ContractEndDate { get; set; }
        public string ProcessingId { get; set; }
    
        public virtual Admin_Organisation Admin_Organisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_Patient> Admin_Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_Patient> Admin_Patient1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment_SessionUser> Appointment_SessionUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Consultation> CareRecord_Consultation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Consultation> CareRecord_Consultation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Diary> CareRecord_Diary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Diary> CareRecord_Diary1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Observation> CareRecord_Observation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Observation> CareRecord_Observation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Problem> CareRecord_Problem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescribing_DrugRecord> Prescribing_DrugRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescribing_DrugRecord> Prescribing_DrugRecord1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescribing_IssueRecord> Prescribing_IssueRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescribing_IssueRecord> Prescribing_IssueRecord1 { get; set; }
    }
}
