//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin_Patient()
        {
            this.Appointment_Slot = new HashSet<Appointment_Slot>();
            this.CareRecord_Consultation = new HashSet<CareRecord_Consultation>();
            this.Prescribing_DrugRecord = new HashSet<Prescribing_DrugRecord>();
            this.Prescribing_IssueRecord = new HashSet<Prescribing_IssueRecord>();
        }
    
        public string PatientGuid { get; set; }
        public string OrganisationGuid { get; set; }
        public string UsualGpUserInRoleGuid { get; set; }
        public string Sex { get; set; }
        public string DateOfBirth { get; set; }
        public string DateOfDeath { get; set; }
        public string Title { get; set; }
        public string GivenName { get; set; }
        public string MiddleNames { get; set; }
        public string Surname { get; set; }
        public string DateOfRegistration { get; set; }
        public string NhsNumber { get; set; }
        public string PatientNumber { get; set; }
        public string PatientTypeDescription { get; set; }
        public string DummyType { get; set; }
        public string HouseNameFlatNumber { get; set; }
        public string NumberAndStreet { get; set; }
        public string Village { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string ResidentialInstituteCode { get; set; }
        public string NHSNumberStatus { get; set; }
        public string CarerName { get; set; }
        public string CarerRelation { get; set; }
        public string PersonGuid { get; set; }
        public string DateOfDeactivation { get; set; }
        public string Deleted { get; set; }
        public string SpineSensitive { get; set; }
        public string IsConfidential { get; set; }
        public string EmailAddress { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string ExternalUsualGPGuid { get; set; }
        public string ExternalUsualGP { get; set; }
        public string ExternalUsualGPOrganisation { get; set; }
        public string ProcessingId { get; set; }
    
        public virtual Admin_Organisation Admin_Organisation { get; set; }
        public virtual Admin_Organisation Admin_Organisation1 { get; set; }
        public virtual Admin_UserInRole Admin_UserInRole { get; set; }
        public virtual Admin_UserInRole Admin_UserInRole1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment_Slot> Appointment_Slot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Consultation> CareRecord_Consultation { get; set; }
        public virtual CareRecord_Diary CareRecord_Diary { get; set; }
        public virtual CareRecord_Observation CareRecord_Observation { get; set; }
        public virtual CareRecord_ObservationReferral CareRecord_ObservationReferral { get; set; }
        public virtual CareRecord_Problem CareRecord_Problem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescribing_DrugRecord> Prescribing_DrugRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescribing_IssueRecord> Prescribing_IssueRecord { get; set; }
    }
}
