//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment_Slot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment_Slot()
        {
            this.CareRecord_Consultation = new HashSet<CareRecord_Consultation>();
        }
    
        public string SlotGuid { get; set; }
        public string AppointmentDate { get; set; }
        public string AppointmentStartTime { get; set; }
        public string PlannedDurationInMinutes { get; set; }
        public string PatientGuid { get; set; }
        public string SendInTime { get; set; }
        public string LeftTime { get; set; }
        public string DidNotAttend { get; set; }
        public string PatientWaitInMin { get; set; }
        public string AppointmentDelayInMin { get; set; }
        public string ActualDurationInMinutes { get; set; }
        public string OrganisationGuid { get; set; }
        public string SessionGuid { get; set; }
        public string DnaReasonCodeId { get; set; }
        public string Deleted { get; set; }
        public string ProcessingId { get; set; }
    
        public virtual Admin_Organisation Admin_Organisation { get; set; }
        public virtual Admin_Patient Admin_Patient { get; set; }
        public virtual Appointment_Session Appointment_Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Consultation> CareRecord_Consultation { get; set; }
    }
}
