//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment_Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment_Session()
        {
            this.Appointment_Slot = new HashSet<Appointment_Slot>();
        }
    
        public string AppointmentSessionGuid { get; set; }
        public string Description { get; set; }
        public string LocationGuid { get; set; }
        public string SessionTypeDescription { get; set; }
        public string SessionCategoryDisplayName { get; set; }
        public string StartDate { get; set; }
        public string StartTime { get; set; }
        public string EndDate { get; set; }
        public string EndTime { get; set; }
        public string Private { get; set; }
        public string OrganisationGuid { get; set; }
        public string Deleted { get; set; }
        public string ProcessingId { get; set; }
    
        public virtual Admin_Location Admin_Location { get; set; }
        public virtual Admin_Organisation Admin_Organisation { get; set; }
        public virtual Appointment_SessionUser Appointment_SessionUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment_Slot> Appointment_Slot { get; set; }
    }
}
