//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment_SessionUser
    {
        public string SessionGuid { get; set; }
        public string UserInRoleGuid { get; set; }
        public string Deleted { get; set; }
        public string ProcessingId { get; set; }
    
        public virtual Admin_UserInRole Admin_UserInRole { get; set; }
        public virtual Appointment_Session Appointment_Session { get; set; }
    }
}
