//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareRecord_Problem
    {
        public string ObservationGuid { get; set; }
        public string PatientGuid { get; set; }
        public string OrganisationGuid { get; set; }
        public string ParentProblemObservationGuid { get; set; }
        public string Deleted { get; set; }
        public string Comment { get; set; }
        public string EndDate { get; set; }
        public string EndDatePrecision { get; set; }
        public string ExpectedDuration { get; set; }
        public string LastReviewDate { get; set; }
        public string LastReviewDatePrecision { get; set; }
        public string LastReviewUserInRoleGuid { get; set; }
        public string ParentProblemRelationship { get; set; }
        public string ProblemStatusDescription { get; set; }
        public string SignificanceDescription { get; set; }
        public string ProcessingId { get; set; }
    
        public virtual Admin_Organisation Admin_Organisation { get; set; }
        public virtual Admin_Patient Admin_Patient { get; set; }
        public virtual Admin_UserInRole Admin_UserInRole { get; set; }
    }
}
