//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareRecord_Consultation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CareRecord_Consultation()
        {
            this.CareRecord_Diary = new HashSet<CareRecord_Diary>();
            this.CareRecord_Observation = new HashSet<CareRecord_Observation>();
        }
    
        public string ConsultationGuid { get; set; }
        public string PatientGuid { get; set; }
        public string OrganisationGuid { get; set; }
        public string EffectiveDate { get; set; }
        public string EffectiveDatePrecision { get; set; }
        public string EnteredDate { get; set; }
        public string EnteredTime { get; set; }
        public string ClinicianUserInRoleGuid { get; set; }
        public string EnteredByUserInRoleGuid { get; set; }
        public string AppointmentSlotGuid { get; set; }
        public string ConsultationSourceTerm { get; set; }
        public string ConsultationSourceCodeId { get; set; }
        public string Complete { get; set; }
        public string Deleted { get; set; }
        public string IsConfidential { get; set; }
        public string ProcessingId { get; set; }
    
        public virtual Admin_Organisation Admin_Organisation { get; set; }
        public virtual Admin_Patient Admin_Patient { get; set; }
        public virtual Admin_UserInRole Admin_UserInRole { get; set; }
        public virtual Admin_UserInRole Admin_UserInRole1 { get; set; }
        public virtual Appointment_Slot Appointment_Slot { get; set; }
        public virtual Coding_ClinicalCode Coding_ClinicalCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Diary> CareRecord_Diary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Observation> CareRecord_Observation { get; set; }
    }
}
