//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareRecord_Observation
    {
        public string ObservationGuid { get; set; }
        public string PatientGuid { get; set; }
        public string OrganisationGuid { get; set; }
        public string EffectiveDate { get; set; }
        public string EffectiveDatePrecision { get; set; }
        public string EnteredDate { get; set; }
        public string EnteredTime { get; set; }
        public string ClinicianUserInRoleGuid { get; set; }
        public string EnteredByUserInRoleGuid { get; set; }
        public string ParentObservationGuid { get; set; }
        public string CodeId { get; set; }
        public string ProblemGuid { get; set; }
        public string AssociatedText { get; set; }
        public string ConsultationGuid { get; set; }
        public string Value { get; set; }
        public string NumericUnit { get; set; }
        public string ObservationType { get; set; }
        public string NumericRangeLow { get; set; }
        public string NumericRangeHigh { get; set; }
        public string DocumentGuid { get; set; }
        public string Deleted { get; set; }
        public string IsConfidential { get; set; }
        public string ProcessingId { get; set; }
    
        public virtual Admin_Organisation Admin_Organisation { get; set; }
        public virtual Admin_Patient Admin_Patient { get; set; }
        public virtual Admin_UserInRole Admin_UserInRole { get; set; }
        public virtual Admin_UserInRole Admin_UserInRole1 { get; set; }
        public virtual CareRecord_Consultation CareRecord_Consultation { get; set; }
        public virtual Coding_ClinicalCode Coding_ClinicalCode { get; set; }
    }
}
