//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coding_DrugCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coding_DrugCode()
        {
            this.Prescribing_DrugRecord = new HashSet<Prescribing_DrugRecord>();
            this.Prescribing_IssueRecord = new HashSet<Prescribing_IssueRecord>();
        }
    
        public string CodeId { get; set; }
        public string Term { get; set; }
        public string DmdProductCodeId { get; set; }
        public string ProcessingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescribing_DrugRecord> Prescribing_DrugRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescribing_IssueRecord> Prescribing_IssueRecord { get; set; }
    }
}
