//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coding_ClinicalCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coding_ClinicalCode()
        {
            this.CareRecord_Consultation = new HashSet<CareRecord_Consultation>();
            this.CareRecord_Diary = new HashSet<CareRecord_Diary>();
            this.CareRecord_Observation = new HashSet<CareRecord_Observation>();
            this.CareRecord_ObservationReferral = new HashSet<CareRecord_ObservationReferral>();
            this.CareRecord_ObservationReferral1 = new HashSet<CareRecord_ObservationReferral>();
            this.CareRecord_ObservationReferral2 = new HashSet<CareRecord_ObservationReferral>();
            this.Coding_ClinicalCode1 = new HashSet<Coding_ClinicalCode>();
        }
    
        public string CodeId { get; set; }
        public string Term { get; set; }
        public string ReadTermId { get; set; }
        public string SnomedCTConceptId { get; set; }
        public string SnomedCTDescriptionId { get; set; }
        public string NationalCode { get; set; }
        public string NationalCodeCategory { get; set; }
        public string NationalDescription { get; set; }
        public string EmisCodeCategoryDescription { get; set; }
        public string ProcessingId { get; set; }
        public string ParentCodeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Consultation> CareRecord_Consultation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Diary> CareRecord_Diary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_Observation> CareRecord_Observation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_ObservationReferral> CareRecord_ObservationReferral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_ObservationReferral> CareRecord_ObservationReferral1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRecord_ObservationReferral> CareRecord_ObservationReferral2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coding_ClinicalCode> Coding_ClinicalCode1 { get; set; }
        public virtual Coding_ClinicalCode Coding_ClinicalCode2 { get; set; }
    }
}
