//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetGPSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescribing_DrugRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prescribing_DrugRecord()
        {
            this.Prescribing_IssueRecord = new HashSet<Prescribing_IssueRecord>();
        }
    
        public string DrugRecordGuid { get; set; }
        public string PatientGuid { get; set; }
        public string OrganisationGuid { get; set; }
        public string EffectiveDate { get; set; }
        public string EffectiveDatePrecision { get; set; }
        public string EnteredDate { get; set; }
        public string EnteredTime { get; set; }
        public string ClinicianUserInRoleGuid { get; set; }
        public string EnteredByUserInRoleGuid { get; set; }
        public string CodeId { get; set; }
        public string Dosage { get; set; }
        public string Quantity { get; set; }
        public string QuantityUnit { get; set; }
        public string ProblemObservationGuid { get; set; }
        public string PrescriptionType { get; set; }
        public string IsActive { get; set; }
        public string CancellationDate { get; set; }
        public string NumberOfIssues { get; set; }
        public string NumberOfIssuesAuthorised { get; set; }
        public string IsConfidential { get; set; }
        public string Deleted { get; set; }
        public string ProcessingId { get; set; }
    
        public virtual Admin_Organisation Admin_Organisation { get; set; }
        public virtual Admin_Patient Admin_Patient { get; set; }
        public virtual Admin_UserInRole Admin_UserInRole { get; set; }
        public virtual Admin_UserInRole Admin_UserInRole1 { get; set; }
        public virtual Coding_DrugCode Coding_DrugCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescribing_IssueRecord> Prescribing_IssueRecord { get; set; }
    }
}
